In [37]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf
physical_devices =  tf.config.list_physical_devices('GPU')
#tf.config.experimental.set_memory_growth(physical_devices[0], enable=True)


Initialization of Tensors
Mathematical Operations
Indexing
Reshaping

In [22]:
#initialization of tensors
x = tf.constant(4, shape=(1,1), dtype=tf.float32) #matrix tensor
print(x)
t = tf.constant([[1,2,3], [4,5,6]]) #list, also create 2x3 matrix
print(t)

x = tf.ones((3,3))
print(x)
x = tf.zeros((2,3))
x = tf.eye(3) # identity matrix
print(x)
x = tf.random.normal((3,3), mean= 0, stddev=1)
x = tf.random.uniform((1,3), minval=0, maxval=1)
x = tf.range(start=1, limit=10, delta=2)
print(x) # range of vectors

x = tf.cast(x, dtype=tf.float64) #type casting
# tf.float(16,32,64), tf.int(8,16,32,64), tf.bool
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [38]:
#Mathematical operation
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

#element wise
z = tf.add(x,y)
print(z)
z = x + y
print(z)

z = tf.subtract(x,y)
z = x-y
print(z)

z = tf.divide(x,y)
z = x/y

z = tf.multiply(x,y)
z = x*y

z = tf.tensordot(x,y, axes=1)
z = tf.reduce_sum(x*y, axis=0)
print(z)

z = x**5 #elementwise power
print(z)

x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

#Matrix Multiplication
z = tf.matmul(x,y)
print(z)
z = x @ y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor([  1  32 243], shape=(3,), dtype=int32)
tf.Tensor(
[[-0.44363582  0.83790004 -3.1140447   2.4733343 ]
 [-1.7620599  -2.8117507   3.545168   -2.60824   ]], shape=(2, 4), dtype=float32)


In [49]:
#Indexing
x = tf.constant([0,1,1,2,3,1,2,3,8,9])
# print(x[:])
# print(x[1:])
# print(x[1:3])
# print(x[::2])
# print(x[::-1])

indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)

print(x_ind)

tf.Tensor([0 2], shape=(2,), dtype=int32)
